## 00. PyTorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
!nvidia-smi

Thu Aug 28 00:30:02 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.07                 Driver Version: 566.07         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   60C    P0              9W /   60W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Introduction to tensors

### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix
matrix = torch.tensor([[7,8],[6,9]])
matrix

tensor([[7, 8],
        [6, 9]])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# tensor
tensor = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [ ]:
# Create random tensors
random = torch.rand(3,4)
random

tensor([[0.1489, 0.2399, 0.4609, 0.1450],
        [0.1608, 0.5232, 0.4493, 0.6330],
        [0.3074, 0.2216, 0.5050, 0.8216]])

In [ ]:
random.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))   # height, width, color channels
# random_image_size_tensor
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [ ]:
# Creating a tensor of all zeroes
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# creating a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
# Creating a range of tensors and tensors-like
torch.arange(0,11)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_hundred = torch.arange(start=1, end=101, step=5)
one_to_hundred

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [ ]:
one_to_hundred = torch.arange(1,101,5)
one_to_hundred

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [ ]:
torch.__version__

'2.8.0+cu126'

In [ ]:
one_to_ten = torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

### Tensor Datatypes

**Note: ** Tensor datatypes is one of the 3 big errors with Pytorch and deep learning
1. Tensor not right datatypes
2. Tensor not right shape
3. Tensor not on right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor.dtype
# Default data type in pytorch is float 32

torch.float32

In [ ]:
# Float 16 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
(int_32_tensor * float_16_tensor).dtype

torch.float16

### Getting information from tensors

**Note: ** Tensor datatypes is one of the 3 big errors with Pytorch and deep learning
1. Tensor not right datatypes -  to do get datatypefrom a tensor, can use `tensor.dtype`
2. Tensor not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensor not on right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6470, 0.0859, 0.6920, 0.4188],
        [0.8510, 0.4577, 0.3802, 0.4436],
        [0.8623, 0.4050, 0.5023, 0.9981]])

In [ ]:
# Find out details about some tensors
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.size())
print(some_tensor.device)

tensor([[0.6470, 0.0859, 0.6920, 0.4188],
        [0.8510, 0.4577, 0.3802, 0.4436],
        [0.8623, 0.4050, 0.5023, 0.9981]])
torch.float32
torch.Size([3, 4])
torch.Size([3, 4])
cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

In [ ]:
# Creating a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
# Try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

# Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning.

1. Element wise multiplication
2. Matrix Multiplication (dot product)

In [ ]:
# Element wise multiplication
print(tensor,"*", tensor,"= ",tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) =  tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 212 µs, sys: 1.04 ms, total: 1.25 ms
Wall time: 12 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 39 µs, sys: 6 µs, total: 45 µs
Wall time: 47.9 µs


tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
random1 = torch.rand(3,2)
random2 = torch.rand(2,3)
random1 @ random2

tensor([[1.0855, 1.1600, 1.4410],
        [0.6886, 0.6814, 0.5259],
        [0.1413, 0.1894, 0.4615]])

### One of the most common errors in deep learning : shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,8],[9,10],[11,12]])
# torch.mm(tensor_A, tensor_B)      # torch.mm is shortcut for writing torch.matmul
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using `transpose`

In [ ]:
print(tensor_B)
print(tensor_B.T)

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
tensor([[ 7,  9, 11],
        [ 8, 10, 12]])


In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [ ]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Creating a tensor
x = torch.arange(0,101,10)
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
# Finding the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Finding the max
torch.max(x), x.max()

(tensor(100), tensor(100))

In [ ]:
# Finding the mean
# torch.mean(x)
# RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

Mean requires the input data type to be float value

In [ ]:
torch.mean(x, dtype=torch.float16), x.type(torch.float32).mean()

(tensor(50., dtype=torch.float16), tensor(50.))

In [ ]:
# Finding the sum
torch.sum(x)

tensor(550)

### Finding the positional max and min

In [ ]:
# Find the position that thas min value
x.argmin()

tensor(0)

In [ ]:
# Find the position that thas max value
x.argmax()

tensor(10)

In [ ]:
x[0], x[10]

(tensor(0), tensor(100))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other `vstack` or side by side `hstack`
* Stacking - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimesions permuted (swapped) in a certain way.

In [ ]:
# Let's create a create a tensor
import torch
x=torch.arange(1.,10.,1)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(3,3)   # we can't write (1,7) because 1X9=9 so it can be written as 3X3 i.e. also 9
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
# Change the view
z = x.view(3,3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked
# dim = 0 : stack row-wise
# dim = 1 : stack column-wise

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [ ]:
# # Example from PyTorch site
# x = torch.zeros(2, 1, 2, 1, 2)
# print(x.size())
# y = torch.squeeze(x)
# print(y.size())
# y = torch.squeeze(x, 0)
# print(y.size())
# y = torch.squeeze(x, 1)
# print(y.size())
# y = torch.squeeze(x, (1, 2, 3))
# print(y)

In [ ]:
x_reshaped = x_reshaped.reshape(1,9)
x_reshaped

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

#### torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension (dim)

In [ ]:
x_unsqueezed_dim0 = x_squeezed.unsqueeze(dim=0)
x_unsqueezed_dim0

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [ ]:
x_unsqueezed_dim0.shape

torch.Size([1, 9])

In [ ]:
x_unsqueezed_dim1 = x_squeezed.unsqueeze(dim=1)
x_unsqueezed_dim1

tensor([[5.],
        [2.],
        [3.],
        [5.],
        [5.],
        [6.],
        [5.],
        [8.],
        [9.]])

In [ ]:
x_unsqueezed_dim1.shape

torch.Size([9, 1])

#### torch.permute() - rearranges the dimensions of a target tensors in a specified order

In [ ]:
x_original = torch.rand(size=(224,224,3))

# permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2,0,1)    # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: \n {x_original}")
print(f"New Shape: \n {x_permuted}")

Previous shape: 
 tensor([[[0.7279, 0.2080, 0.7500],
         [0.9418, 0.9734, 0.0883],
         [0.1822, 0.8224, 0.4846],
         ...,
         [0.0486, 0.1084, 0.3177],
         [0.6568, 0.5615, 0.0738],
         [0.9598, 0.4794, 0.8584]],

        [[0.2301, 0.7167, 0.4093],
         [0.9552, 0.1449, 0.4522],
         [0.2283, 0.0989, 0.3391],
         ...,
         [0.6494, 0.5337, 0.8383],
         [0.7566, 0.0025, 0.1829],
         [0.7746, 0.1194, 0.7034]],

        [[0.1626, 0.0370, 0.1863],
         [0.3756, 0.5553, 0.4115],
         [0.9828, 0.1783, 0.3214],
         ...,
         [0.6606, 0.9749, 0.9315],
         [0.6327, 0.1962, 0.5423],
         [0.8594, 0.3396, 0.0735]],

        ...,

        [[0.2765, 0.3760, 0.5441],
         [0.8820, 0.8764, 0.8128],
         [0.5880, 0.3519, 0.4472],
         ...,
         [0.7135, 0.8160, 0.5806],
         [0.8800, 0.5799, 0.4219],
         [0.2541, 0.7207, 0.4814]],

        [[0.4827, 0.3636, 0.3203],
         [0.0270, 0.5242, 0.2

In [ ]:
x_original[0,:10, :]

tensor([[0.7279, 0.2080, 0.7500],
        [0.9418, 0.9734, 0.0883],
        [0.1822, 0.8224, 0.4846],
        [0.8329, 0.8480, 0.3088],
        [0.5981, 0.2342, 0.1690],
        [0.7593, 0.5485, 0.5287],
        [0.5205, 0.1261, 0.2907],
        [0.9658, 0.6964, 0.8363],
        [0.5381, 0.4061, 0.3970],
        [0.5759, 0.8869, 0.2495]])

In [ ]:
x_original[0,0,0]= 696969
x_original[0,0,0], x_permuted[0,0,0]

(tensor(696969.), tensor(696969.))

## Indexing (selecting data from tensors)

Similar to Numpy

In [ ]:
# Create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Indexing new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
# We can use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

## PyTorch and Numpy

* Data in Numpy array want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor to Numpy array -> torch.Tensor.numpy()

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype, tensor.dtype, torch.arange(1.0,8.0).dtype

(dtype('float64'), torch.float64, torch.float32)

In [ ]:
# change the in array, what will happen in tensor
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor.dtype, numpy_tensor.dtype

(torch.float32, dtype('float32'))

In [ ]:
# change the tensor, what happens with numpy
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> repeat -> repeat -> repeat...`

To reduce the randomness in neural networks and PyTorch comes the concept of **random seed**.

Essentially, random seed 'flavour' the randomness.

In [ ]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3330, 0.3679, 0.2087, 0.3844],
        [0.1652, 0.4751, 0.9881, 0.3626],
        [0.9330, 0.7130, 0.9873, 0.9688]])
tensor([[0.4547, 0.7793, 0.7797, 0.9140],
        [0.2540, 0.4075, 0.2262, 0.1240],
        [0.1541, 0.3448, 0.9279, 0.0270]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible function
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

# create random tensor
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resouces for reproducibility :

* https://docs.pytorch.org/docs/2.8/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computation)

GPUs = faster computation on numbers

### 1. Getting a GPU

1. Easiest - Use Google collab
2. Using own GPU - takes a little bit of setup and requires the purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow to rent computer on cloud and use them

### 2. Check for GPU access with pytorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
# Count number of GPUs
torch.cuda.device_count()

1

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://docs.pytorch.org/docs/stable//notes/cuda.html

E.g. run on GPU if available, else set to CPU

### 3. Putting tensors and models on GPU

Using a GPU results in faster calculations.

In [ ]:
# create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the cpu

In [ ]:
# If tensor is on GPU, we can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with numpy issue, first set it to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

### PyTorch Exercises
* https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises
* https://github.com/mrdbourke/pytorch-deep-learning/tree/main/extras/exercises